РК1
frontend-park-mail-ru/2023_2_OND_team pull request #2
Opened 2023-10-03 12:35 UTC by muslimitsuhide

2023-10-03 20:18 UTC, Ivan-Bir requested changes
Предстоит много рефакторинга
Есть критичные замечания, как работа с куками, верстка в js, css в одном файле, названия классов не по бэму

2023-10-03 20:18 UTC, Ivan-Bir commented on .gitignore
> +.DS_Store
Пустые строки везде посмотри по МР

2023-10-03 20:18 UTC, Ivan-Bir commented on README.md
> +Деплой: https://pinspire.online:1443/
Фигму ещё приложите с апи-докой

2023-10-03 20:18 UTC, Ivan-Bir commented on public/compiledTemplates/templates.hbs.js
А зачем в репе скомпиленные шаблоны?
Удалите и заигнорьте

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
> +    pageElement.style.display = 'blosk';
интересно

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
> +    const cancelButton = document.createElement('button');
Зачем же мучиться?
Есть же замечательные шаблоны.
Вся вёрстка должна быть вынесена в шаблоны

2023-10-03 20:18 UTC, Ivan-Bir commented on public/utils/generatePins.js
> +export async function generatePins() {
Сделайте общий компонент похода в апишку. Чтобы он отвечал только за данные и умел дергать нужные ручки
API.getPins( ... ).then( ... )

2023-10-03 20:18 UTC, Ivan-Bir commented on public/utils/generatePins.js
> +        const response = await fetch('//pinspire.online:8080/api/v1/pin?count=10');
Советую вынести хардкод домена бэка под конфиг

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Registration/reg-page.js
> +    const usernameInput = createLabeledInput('Имя пользователя', 'text', 'username');
Это всё замечательно ложится в шаблон-контейнер благодаря оператору {{{ }}} в hbs
createLabeledInput правильнее заменить на createLabeledInputTemplate и отрендеренный шаблон прокидывать в другой "интегрирующий" шаблон

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Registration/reg-page.js
> +        const username = usernameInput.querySelector('input').value;
давайте никогда не селектить по тэгу. Используя БЭМ вы не боитесь случайно заселектить другой инпут
И давайте использовать отдельные css-классы (с префиксом js-) для использования html-элементов в коде
И так же не используйте id в разметке. Плохо засорять глобальный скоуп

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Registration/reg-page.js
> +            usernameInput.querySelector('input').style.borderColor = 'var(--error-50, #F4210B)';
Как и говорил, переносите в css

2023-10-03 20:18 UTC, Ivan-Bir commented on public/index.html
> +    <script type="module" src="./components/Header/Header.js"></script>
Зачем отдельно вынесли Хедер?
Хэдер обычный кусок вашего приложения. Ему место внутри index.js

2023-10-03 20:18 UTC, Ivan-Bir commented on public/modules/auth.js
> +    fetch('/set-cookie', {
Зачем вам куки на сервер слать?
Если они есть, то обеспечьте, чтобы они отсылались с другими запросами.
Если это метод проверки авторизации, то давайте так его и назовем /auth

2023-10-03 20:18 UTC, Ivan-Bir commented on public/modules/reg.js
> +    fetch('/set-registered-cookie', {
Аналогичный вопрос. Для чего?

2023-10-03 20:18 UTC, Ivan-Bir commented on public/styles.css
> +html, body {
Ой, весь css в одном файле
Есть директива @import
Используйте её в index.css и будет вам счастье декомпозиции

2023-10-03 20:18 UTC, Ivan-Bir commented on public/styles.css
> +@media (max-width: 1400px) {
Молодцы, что сделали, но это очень рано
Адаптивная верстка будет к 3-му рк

2023-10-03 20:18 UTC, Ivan-Bir commented on public/styles.css
> +  font-size: 21.25px;
давайте без полпикселя

2023-10-03 20:18 UTC, Ivan-Bir commented on public/styles.css
> +}
Пустые строки, говорил

2023-10-03 20:18 UTC, Ivan-Bir commented on public/utils/cookie.js
> +    document.cookie = name + "=" + value + ";" + expires + ";path=/";
эммммм
На второй лекции не рассказывали, что фронт не должен *вообще* трогать куки?

2023-10-03 20:18 UTC, Ivan-Bir commented on public/utils/login.js
> +import { setCookie } from '../utils/cookie.js';
дока уехала

2023-10-03 20:18 UTC, Ivan-Bir commented on public/utils/valid.js
> +/**
isValidUserNameInput.js
Давайте чуть понятнее называть свои модули

2023-10-03 20:18 UTC, Ivan-Bir commented on public/utils/valid.js
> +        nameMessage = 'Имя пользователя должно содержать не менее 8 символов.';
Странное требование. Зачем ограничиваете?

2023-10-03 20:18 UTC, Ivan-Bir commented on public/index.js
> +const headerElement = document.createElement('header');
Не надо в индексе создавать какие-то элементы. Точка входа должна просто запустить ваше приложение.
Хочется видеть просто renderMainPage();

2023-10-03 20:18 UTC, Ivan-Bir commented on server/index.js
> +        images: [
Зачем в юзере отдавать картинки?
Картинки это отдельная история

Да и как сейчас сделано не прокатит.
1)Вы, что же, хотите в сервисе для картинок показывать картинки с других сервисов?
2) Надо научиться хранить картинки на *бэке* и правильно отдавать. Ладно статичные картинки - как боковая картинка при логине, реге. Но это динамичный контент, и такую логику, пусть даже с 10-ю картинками, должен делать бэкенд.

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Feed/Feed.js
> +            const section = document.getElementById('pins');
Навесьте хоть какой-нибудь эффект ховера на картинку, а то вообще выглядит неживым

2023-10-03 20:18 UTC, Ivan-Bir commented on public/components/Header/Header.js
> +export class Header {
Хочу нажимать на лого сайта и попадать на главную(если на ней, то наверх)
Давайте не лишать пользователей их привычных функций на сайте

2023-10-03 22:34 UTC, muslimitsuhide commented on public/components/Feed/Feed.js
> +            const section = document.getElementById('pins');
сделано✅

2023-10-03 22:34 UTC, muslimitsuhide commented on README.md
> +Деплой: https://pinspire.online:1443/
сделано✅

2023-10-04 00:00 UTC, muslimitsuhide commented on public/styles.css
> +html, body {
сделано✅

2023-10-04 00:01 UTC, muslimitsuhide commented on public/styles.css
> +@media (max-width: 1400px) {
ладно

2023-10-04 00:03 UTC, muslimitsuhide commented on public/utils/login.js
> +import { setCookie } from '../utils/cookie.js';
поправил✅

2023-10-04 00:11 UTC, muslimitsuhide commented on public/utils/valid.js
> +        nameMessage = 'Имя пользователя должно содержать не менее 8 символов.';
договорились, что `username` у нас будет в промежутке от 4 символов до 50.
подправил это в коде✅

2023-10-04 00:41 UTC, muslimitsuhide commented on public/index.js
> +const headerElement = document.createElement('header');
окей, переделал✅

2023-10-04 01:03 UTC, muslimitsuhide commented on public/utils/valid.js
> +/**
исправил✅

2023-10-04 01:13 UTC, muslimitsuhide commented on public/index.html
> +    <script type="module" src="./components/Header/Header.js"></script>
вынесли хэдер как отдельный компонент, так как он имеет несколько состояний (в зависимости от того, авторизован ли пользователь или нет)

2023-10-04 01:52 UTC, muslimitsuhide commented on .gitignore
> +.DS_Store
сделано✅

2023-10-04 02:41 UTC, muslimitsuhide commented on public/styles.css
> +}
сделано✅

2023-10-04 02:42 UTC, muslimitsuhide commented on public/styles.css
> +  font-size: 21.25px;
сделано✅

2023-10-04 03:50 UTC, Romanlock commented on public/components/Header/Header.js
> +export class Header {
Пользователь будет доволен - теперь лого кликабельны 👍

2023-10-04 03:54 UTC, Romanlock commented on public/modules/auth.js
> +    fetch('/set-cookie', {
устранил 👍

2023-10-04 03:55 UTC, Romanlock commented on public/modules/reg.js
> +    fetch('/set-registered-cookie', {
аналогично устранил 👍

2023-10-04 03:55 UTC, Romanlock commented on public/utils/cookie.js
> +    document.cookie = name + "=" + value + ";" + expires + ";path=/";
теперь фронт вообще не работает с куки 👍

2023-10-04 04:08 UTC, Romanlock commented on public/index.js
> +const headerElement = document.createElement('header');
сделал 👍

2023-10-04 04:14 UTC, Romanlock commented on server/index.js
> +        images: [
устранил 👍

2023-10-04 04:15 UTC, Romanlock commented on server/index.js
> +        images: [
теперь вся динамика раздается с бэка

2023-10-04 08:15 UTC, Romanlock commented on public/utils/generatePins.js
> +export async function generatePins() {
готово 👍

2023-10-04 08:15 UTC, Romanlock commented on public/utils/generatePins.js
> +        const response = await fetch('//pinspire.online:8080/api/v1/pin?count=10');
сделано 👍

2023-10-04 08:17 UTC, Romanlock commented on public/styles.css
> +@media (max-width: 1400px) {
я старался)

2023-10-05 20:09 UTC, Ivan-Bir requested changes
В целом хорошо, мне нравится как вы идёте
Поправьте замечания и по предыдущему ревью
Больше всего вопросов про взаимодействие с css через js и по декомпозиции

2023-10-05 20:09 UTC, Ivan-Bir commented on public/compiledTemplates/templates.hbs.js
не удаляется?

2023-10-05 20:09 UTC, Ivan-Bir commented on .eslintrc.js
> +        "@typescript-eslint"
Раньше времени ts не надо трогать

2023-10-05 20:09 UTC, Ivan-Bir commented on README.md
> +Деплой: https://pinspire.online:1443/
Где ссылка на сваггер?

2023-10-05 20:09 UTC, Ivan-Bir commented on .gitignore
>  *.pem
package-lock.json не надо в игнор. Там у вас закрепляются все зависимости вместе с подзависимостями. Через npm ci я смогу даже спустя время полностью накатить нужные версии пакетов

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
>  import { renderRegPage } from '../Registration/reg-page.js';
Давайте немного изменим структуру проекта. Всё-таки /public это директория, в которой должен лежать собранный код проекта. Все исходники обычно складывают в /src

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
>  import { renderRegPage } from '../Registration/reg-page.js';
Не удобнее разве складывать в components вместе hbs, css и js? Тогда будет и смысл в директориях для каждого компонента. Css не сказать что статика. А вот иконки, картинки интерфейса, шрифты статика

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
>  import { renderRegPage } from '../Registration/reg-page.js';
К этому или следующему рк давайте найдем какой-нибудь классный шрифт и научимся пользоваться в проекте не только дефолтными шрифтами

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
> +        if (!usernameValidationResult.valid) {
Вынести эту логику под функцию. Использование должно быть максимально простым.
Если идейно смотреть на это. Страница должна просто знать какие компоненты она содержит и как они могут взаимодействовать друг с другом. Логика валидации должна быть внутри формы, не на странице.

И не надо вручную обновлять стили, здесь вы можете накинуть новый класс, который перебьет основные стили, либо удалить класс через js. Но не писать стили таким образом :)

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Authorization/auth-page.js
> +// export function renderAuthPage(headerElement, pageElement) {
коменты

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Feed/Feed.js
> +// import { handleScroll } from "../../utils/handleScroll.js";
еще коменты
Проверьте везде перед финальным МР

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Feed/Feed.js
> +}
пустая строка

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Header/Header.js
> +        this.#Api = new API();
Вообще класс API можно сделать статическим и дергать методы не прибегая к созданию инстанса

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Registration/reg-page.js
> +    const Api = new API();
Да, именно поэтому статический класс удобнее

2023-10-05 20:09 UTC, Ivan-Bir commented on public/components/Registration/reg-page.js
> +        const username = usernameInput.querySelector('input').value;
Не вижу изменений

2023-10-05 20:09 UTC, Ivan-Bir commented on public/static/css/form.css
> +    overflow:  hidden;
Картинка сжимается/расширяется на разных разрешениях, в помощь
object-fit: cover;

2023-10-05 20:09 UTC, Ivan-Bir commented on public/static/css/header.css
> +    border: 2px solid var(--primary-30, #226B77);
решение интересное, но вам трудно что-то менять и в коде и в стилях
Если сделаете отдельный класс, который будете навешивать в разной логике, то это сильно упростит жизнь

2023-10-05 20:09 UTC, Ivan-Bir commented on public/utils/api.js
> +
Если требуется всё-таки создавать инстанс, то тогда в помощь синглтон
export default new API()

2023-10-05 20:09 UTC, Ivan-Bir commented on public/utils/valid.js
> +        validation = { valid: false, message: 'Email должен содержать не более 50 символов' };
то есть 50 или больше, а в условии не так)

2023-10-05 20:15 UTC, Ivan-Bir requested changes

2023-10-05 20:15 UTC, Ivan-Bir commented on public/components/Header/Header.js
> +import { renderRegPage } from "../Registration/reg-page.js";
Давайте везде придерживаться одного стиля нейминга файлов. CamelCase кажется больше подходит

2023-10-05 20:15 UTC, Ivan-Bir commented on public/components/Feed/Feed.js
> +        const rootElement = document.getElementById('root');
Root можно сделать синглтоном

2023-10-05 20:15 UTC, Ivan-Bir commented on public/components/Feed/Feed.js
> +        pageElement = document.createElement('main');
шаблоны, ребята, шаблоны. Не стоит изгаляться с кастомными тэгами. div всё стерпит и правильно названные css-классы не помешают в навигации по структуре dom

2023-10-05 22:17 UTC, muslimitsuhide commented on .eslintrc.js
> +        "@typescript-eslint"
ок

2023-10-05 22:17 UTC, muslimitsuhide commented on .gitignore
>  *.pem
ок

2023-10-06 00:34 UTC, muslimitsuhide commented on public/static/css/form.css
> +    overflow:  hidden;
сделано🌚

2023-10-06 00:45 UTC, muslimitsuhide commented on public/utils/valid.js
> +        validation = { valid: false, message: 'Email должен содержать не более 50 символов' };
забавно вышло 
исправил)

2023-10-06 00:48 UTC, muslimitsuhide commented on public/components/Authorization/auth-page.js
> +// export function renderAuthPage(headerElement, pageElement) {
это шаблоны прикрутить пробовал...
уберу, конечно же

2023-10-06 05:39 UTC, Romanlock commented on public/components/Feed/Feed.js
> +}
устранил👍

2023-10-06 05:39 UTC, Romanlock commented on public/components/Header/Header.js
> +        this.#Api = new API();
сделал 👍

2023-10-06 05:40 UTC, Romanlock commented on public/utils/api.js
> +
сделал статический класс 👍

2023-10-06 07:20 UTC, Romanlock commented on public/components/Authorization/auth-page.js
> +    const cancelButton = document.createElement('button');
Всё сделано 👍

2023-10-06 07:21 UTC, Romanlock commented on public/index.html
> +    <script type="module" src="./components/Header/Header.js"></script>
Теперь рендерим все за раз через feed 👍

2023-10-06 07:24 UTC, Romanlock commented on public/components/Feed/Feed.js
> +        pageElement = document.createElement('main');
Сделано 👍

2023-10-06 14:35 UTC, merged