WebPack
frontend-park-mail-ru/2023_2_OND_team pull request #5
Opened 2023-11-02 18:30 UTC by muslimitsuhide

2023-11-02 23:26 UTC, Ivan-Bir requested changes

2023-11-02 23:26 UTC, Ivan-Bir commented on dist/bundle.js
Это убрать из репы

2023-11-02 23:26 UTC, Ivan-Bir commented on public/router/page-routes.js
> +const router = express.Router();
Так-с
Это что за единороги?
У нас на курсе НЕЛЬЗЯ использовать клиентские библиотеки
Написав const express = require('express') ты добавил себе в бандл весь код библиотеки
Да и смысла для этого нет
Для определения пути достаточно посмотреть в window.location и хранить текущую страницу в стейте приложения, и навесить слушатели событий на изменения активной страницы

2023-11-02 23:26 UTC, Ivan-Bir commented on webpack.config.js
> +        test: /\.css$/,
можешь сразу и препрцессор scss тут прикрутить как-то так
{
                test: /\.(s[ac])ss$/i,
                use: ["sass-loader"],
            },

2023-11-02 23:26 UTC, Ivan-Bir commented on webpack.config.js
> +  output: {
Советую почитать что такое publicPath
https://stackoverflow.com/questions/28846814/what-does-publicpath-in-webpack-do

2023-11-02 23:26 UTC, Ivan-Bir commented on webpack.config.js
> +    filename: 'bundle.js',
При дебаге советую отключать кэш в браузере, чтобы не было сюрпризов
Или так же сюда хэш добавить filename: 'bundle.[contenthash].js',

2023-11-02 23:28 UTC, muslimitsuhide commented on public/router/page-routes.js
> +const router = express.Router();
упс, это были эксперименты, забыл убрать)

2023-11-05 09:21 UTC, Ivan-Bir commented on dist/index.html
убрать всю папку dist

2023-11-23 22:42 UTC, closed without merging